name: Publish to Exploitables Repository Release
# Publish manually
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publish
        env:
          ExploitablesReposiliteReleasesUsername: ${{ secrets.MAVEN_NAME }} # token
          ExploitablesReposiliteReleasesPassword: ${{ secrets.MAVEN_TOKEN }} # password
